apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-quality-cli
  labels:
    version: 0.0.0
spec:
  template:
    metadata:
      labels:
        version: 0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: test-quality-cli
  labels:
    version: 0.0.0
